### ISSUE TITLE
Darkroom leaks mmap mappings

### ISSUE THREAD

**Issue by expipiplus1** [jameshegarty/darkroom#2]
To reproduce:

1. Create a object file exporting a darkroom processing function
2. Call the exported function repeatedly
3. Observe a crash in `makeCircular` after one of the calls to `mmap` fails with `ENOMEM`

Investigating the darkroom source, there don't seem to be any calls to `munmap`.

**Comment by jameshegarty** [comment]
Hey. I wasn't able to replicate the crash on my machines here, but I did check in a change to correctly call unmap. Let me know if this solves the problem for you.
