### ISSUE TITLE
High overhead calling compiled darkroom function.

### ISSUE THREAD

**Issue by expipiplus1** [jameshegarty/darkroom#3]
These stats were generated using the identity function and the canny edge detection function from the examples directory being run 600 times over some image data.

identity function:
256x256:   31.0 MPix/s
1080x1920: 230.0 MPix/s

canny edge detection:
256x256:   2.6 MPix/s
1080x1920: 7.6 MPix/s

There seems to be quite some overhead involved into the call to the compiled darkroom function. As far as I can tell this is due to the compiled code performing several memory allocations, and the mmap calls aren't always cheap.

There doesn't seem to be anything in the docs about amortizing this cost. What methodology was used to get the performance specified in the paper?

**Comment by jameshegarty** [comment]
Hi. It probably wouldn't be that difficult to lift those allocations outside of the function, but no, there isn't a built-in way to do that currently. When I benchmarked this for the paper, I convinced myself that this didn't change the performance by more than a percent or two (on our particular platform, example programs etc). Obviously the current interface is a lot simpler as a result. There is also thread launch overhead btw. 

IMO I still don't think these fixed overheads are significant. But I suppose it's possible there was a regression. Feel free to contact me (jhegarty@stanford.edu) directly with more info about what you're trying to do and I can try to help you out.
